[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=2.11.0",
    "pandas>=2.3.3",
    "pdfplumber>=0.11.8",
    "requests>=2.32.5",
    "streamlit>=1.52.1",
    "tenacity>=9.1.2",
]
